version: "3"
services:

  webserver:
    image: nginx
    mem_limit: 128m
    cpus: 0.5
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    ports:
    - "80:80"

  frontend:
    image: plone/plone-frontend:latest
    mem_limit: 256m
    cpus: 1.0
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
    - "3000:3000"
    depends_on:
      - backend

  backend:
    image: plone/plone-backend:6.0
    mem_limit: 512m
    cpus: 1.0
    environment:
      SITE: Plone
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='db' password='plone'"
    ports:
    - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    mem_limit: 512m
    cpus: 1.5
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    volumes:
    - data:/var/lib/postgresql/data
    ports:
    - "5432:5432"

volumes:
  data: {}